services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gospace
    ports:
      - "${SERVE_PORT:-6060}:${SERVE_PORT:-6060}"
      - "6061-8900:6061-8900"
    volumes:
      - ./gospace:/app
    entrypoint: ["/usr/local/bin/gospace", "-port", "${SERVE_PORT}", "-key", "serve"]
