services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gospace
    environment:
      GOSPACE_CONTROL_TOKEN: ${GOSPACE_CONTROL_TOKEN:-}
    ports:
      - "${SERVE_PORT:-6060}:${SERVE_PORT:-6060}"
    command: ["-port", "${SERVE_PORT:-6060}"]
